In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
import pickle

In [5]:
df = pd.read_csv("../AAPL.csv")

In [6]:
df

Date        Open        High         Low       Close   Adj Close  \
0      1980-12-12    0.513393    0.515625    0.513393    0.513393    0.404953   
1      1980-12-15    0.488839    0.488839    0.486607    0.486607    0.383825   
2      1980-12-16    0.453125    0.453125    0.450893    0.450893    0.355655   
3      1980-12-17    0.462054    0.464286    0.462054    0.462054    0.364458   
4      1980-12-18    0.475446    0.477679    0.475446    0.475446    0.375022   
...           ...         ...         ...         ...         ...         ...   
10007  2020-08-20  463.000000  473.570007  462.929993  473.100006  473.100006   
10008  2020-08-21  477.049988  499.470001  477.000000  497.480011  497.480011   
10009  2020-08-24  514.789978  515.140015  495.750000  503.429993  503.429993   
10010  2020-08-25  498.790009  500.720001  492.209991  499.299988  499.299988   
10011  2020-08-26  504.720001  507.970001  500.329987  506.089996  506.089996   

            Volume  
0      117258400.0  
1       43971200.0  
2       26432000.0  
3       21610400.0  
4       18362400.0  
...            ...  
10007   31726800.0  
10008   84513700.0  
10009   86484400.0  
10010   52873900.0  
10011   40617600.0  

[10012 rows x 7 columns]

In [7]:
new_df = df[["Open","Close"]]

In [8]:
new_df.dropna(inplace=True)

<ipython-input-8-ca20e18b38b5>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.dropna(inplace=True)


In [9]:
new_df

Open       Close
0        0.513393    0.513393
1        0.488839    0.486607
2        0.453125    0.450893
3        0.462054    0.462054
4        0.475446    0.475446
...           ...         ...
10007  463.000000  473.100006
10008  477.049988  497.480011
10009  514.789978  503.429993
10010  498.790009  499.299988
10011  504.720001  506.089996

[10011 rows x 2 columns]

In [10]:
X = new_df["Open"].values

In [11]:
y = new_df["Close"].values

In [12]:
X

array([5.13393000e-01, 4.88839000e-01, 4.53125000e-01, ...,
       5.14789978e+02, 4.98790009e+02, 5.04720001e+02])

In [13]:
y

array([5.13393000e-01, 4.86607000e-01, 4.50893000e-01, ...,
       5.03429993e+02, 4.99299988e+02, 5.06089996e+02])

In [14]:
model = LinearRegression()

In [15]:
X = X.reshape(-1,1)
X

array([[5.13393000e-01],
       [4.88839000e-01],
       [4.53125000e-01],
       ...,
       [5.14789978e+02],
       [4.98790009e+02],
       [5.04720001e+02]])

In [16]:
y = y
y

array([5.13393000e-01, 4.86607000e-01, 4.50893000e-01, ...,
       5.03429993e+02, 4.99299988e+02, 5.06089996e+02])

In [17]:
model.fit(X,y)

LinearRegression()

In [18]:
with open('model.pkl','wb') as pickle_out:
    pickle.dump(model, pickle_out)

In [19]:
model.predict([[600]])

array([600.83261293])